architectury {
    common(enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/${mod_id}.accesswidener")
}



publishing {
    publications {
        mavenCommon(MavenPublication) {
            artifactId = rootProject.mod_id
            from components.java
        }
    }

    repositories {
        // Add repositories to publish to here.
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.output_directory=${new File(rootProject.buildDir, "docsOut")}")
    it.options.compilerArgs.add("-Acrafttweaker.processor.document.multi_source=true")

    it.options.compilerArgs << "-Xmaxerrs" << "4000"

}

dependencies {
    // We depend on fabric loader here to use the fabric @Environment annotations and get the mixin dependencies
    // Do NOT use other classes from fabric loader
    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    implementation(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))

    modApi("net.mehvahdjukaar:moonlight:${moonlight_version}")
    //modCompileOnly("net.mehvahdjukaar:supplementaries:${supplementaries_version}")
    modImplementation("curse.maven:supplementaries-412082:7431873")

    modImplementation("curse.maven:exposure-871755:7667016")
    modCompileOnly("curse.maven:distant-horizons-508933:7375280")
    modCompileOnly("curse.maven:cc-tweaked-282001:5714507")
    modCompileOnly("curse.maven:jei-238222:7391695")
    modCompileOnly("curse.maven:irisshaders-455508:6258195")
    //modCompileOnly("curse.maven:sodium-394468:6260639")


}
